### ISSUE TITLE
GIT issue - add permission for adding Reviewers to new pull requests

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#1701]
I see maybe issue for external GIT contributors. Let me describe the scenario:

1. I created new GIT pull request to mlrun/mlrun original repository
2. Here was no optional for external contributors (people out of iguazio company) to add Reviewers
   - probably based on the missing permission the final merge can take longer time
   - see print screen from my pull request (without ability to add reviewers), but internal people from Iguazio have ability to add reviewers  (I confirm the functionality with Edmond)
![GIT](https://user-images.githubusercontent.com/95856749/151986388-2b8425c9-feaf-4497-8b81-84febdf7285f.png)

**Comment by yaronha** [comment]
@Hedingber can u take a look?

**Comment by Hedingber** [comment]
@george0st 
That's not really in my control, that's just how Github works.
Github doesn't let you define custom repository roles*, they have a closed set of roles you can use.
The default role outside collaborators are being assigned to is the _Read_ role, it allows you to:
> Read and clone repositories. Open and comment on issues and pull requests.

(exact permissions can be found [here](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role))
The next repository role after _Read_ is _Triage_, this one lets you "Read permissions plus manage issues and pull requests." and specific examples: Close a pull request, Delete a discussion, Set milestones
I assume you can understand why the default role for outside contributors is _Read_ and not _Triage_
Specifically because I know you, I can give you _Triage_ permission, just did that, but can't make that the default.

* Github recently announced a [new custom repository roles feature](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization), but it's still in beta, when it will be more stable I might use it to create a Read-like role that also allows to set reviewers

**Comment by george0st** [comment]
@Hedingber, I got it and many thanks.

**Comment by Hedingber** [comment]
Leaving open as a reminder to try and use custom repository roles when it's becoming stable
