### ISSUE TITLE
Installing mlrun on k8s (Desktop Docker) error or warning?

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#1862]
Hello, I installed mlrun in Docker Desktop 4.6.1 (76265) for Windows with WSL2 and I ran the command:
`helm --namespace mlrun install mlrun-kit --wait --set global.registry.url=index.docker.io/aaa --set global.registry.secretName=registry-credentials v3io-stable/mlrun-kit`

I got next error:
`Error: INSTALLATION FAILED: timed out waiting for the condition`

All seems fine based on view to running pods:
![image](https://user-images.githubusercontent.com/95856749/161429912-c5b9afe8-1413-4d27-89b5-699f27e29261.png)

But in case of access to these addresses

- Jupyter-notebook - http://localhost:30040 - **access is OK**
- Nuclio - http://localhost:30050 - **access is OK**
- MLRun UI - http://localhost:30060 - **access is OK**
- MLRun API (external) - http://localhost:30070 - **return only information {"detail":"Not Found"} and it seems ok**

I have a question:

- Is it the error or only warning because all seems fine or how to do double check if an issue exists?

**Comment by Tankilevitch** [comment]
Hey @george0st ,
Thank you for the very detailed issue.
I believe what happened was that because this was your first installation, you had to pull all images, which took longer than the helm install’s timeout. Everything appears to be fine, if you want to double-check, uninstall the chart and then reinstall; this time it will succeed because you already have the images locally.
I will add `--timeout X` to the helm command in our installation guide.
What’s happening here is that you’re accessing the API with empty path, there’s no endpoint there, and therefore you’re getting that 404 not found, you can try and add /api/healthz to the URL and you’ll see that it’s working. I’ll change our docs to point on a valid endpoint for the API URL.

**Comment by george0st** [comment]
I am sure that `--timeout X` covers the issue during first installation (second installation takes only 2 minutes, the first one takes about 15+ minutes) 
![image](https://user-images.githubusercontent.com/95856749/161443549-b0d4584e-8f4e-4f26-98e2-2861fe6ce36d.png)

And thanks for information about API testing (I am going to check that).

**Comment by george0st** [comment]
The [localhost:30070/api/healthz](http://localhost:30070/api/healthz) works, thanks see dump
`{"version":"0.10.0","namespace":"mlrun","docker_registry":"index.docker.io/aaa","remote_host":"","mpijob_crd_version":"v1","ui_url":"","artifact_path":"/home/jovyan/data","spark_app_image":"","spark_app_image_tag":"","spark_history_server_path":"","spark_operator_version":null,"kfp_image":"mlrun/mlrun:0.10.0",...`

It will be fine/nice to mention in [Install guide](https://docs.mlrun.org/en/latest/install-kubernetes.html) also:
 - --timeout X
 - http://[localhost:30070/api/healthz](http://localhost:30070/api/healthz) , it is very useful
 - information about minimal memory (when I used in .wslconfig only memory=2GB, it was not possible to run UI, I saw recommendation but it will be fine to mention minimalistic valid size also)
 - what about to mention also setting 'Expose daemon on tcp://localhost:2375 without TLS' (it is in last version Docker Desktop 4.6.1 (76265) in other case the valid certificate is needed)

BTW: I am not sure, if it makes sense to mention also Switch - Show system containers (advanced) see picture:
![image](https://user-images.githubusercontent.com/95856749/161444792-c66587ca-8f69-42ac-b2cb-7ea96dd36901.png)

Many thanks for excellent work and support.

**Comment by george0st** [comment]
See https://github.com/mlrun/mlrun/pull/1865
