### ISSUE TITLE
Document the MLRun CLI

### ISSUE THREAD

**Issue by tebeka** [mlrun/mlrun#203]
We should document the `mlrun` command line.
Maybe using the [sphinx-click](https://sphinx-click.readthedocs.io/en/latest/) extension.

**Comment by Sharon-iguazio** [comment]
@tebeka as part of my current doc review I also reviewed the CLI help text in **mlrun/__main__.py**; I'll submit a PR shortly.
Regarding generating documentation from the help text, this is up to @yaronha. I definitely won't have the time to investigate and implement a tool for this. => Reassigning to Yaron.

I can tell you, thought, that Nuclio has a Go tool for generating CLI Markdown reference doc from the help text, and while initially we incorporated this doc in the GitHub doc and on the doc site, this was soon abandoned because R&D didn't regenerate the help text for each new release, so it was decided to remove the CLI doc and refer to the CLI help. But if you add something automatic like the mlrun API doc generation, of course that would be good.
