### ISSUE TITLE
[Docs]: Add documentation for mlrun.feature_store.feature_set.FeatureSetSpec

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2312]
### MLRun Kit version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://docs.mlrun.org/en/latest/)

### Location of the documentation

`https://docs.mlrun.org/en/latest/api/mlrun.feature_store.html#mlrun.feature_store.FeatureSet.spec`

### Documentation problem

Missing documentation for this class (it is without generation of documentation but some parts of source code contains relevant documentation)

### Suggested fix for documentation

Please, generate documentation also for this class

**Comment by theSaarco** [comment]
Hi @george0st,  the `FeatureSetSpec` class is an internal member of the `FeatureSet` class, and you're seeing it in the docs just because `FeatureSet` has a property that returns it. We usually don't expect users to work directly with this class, but rather through the `FeatureSet` class or the feature-store apis. Given that, there doesn't seem to be a lot of value in documenting this class. We can of course add a general note on the class saying pretty much what I just noted.
What do you think? I'm interested to get your view and expectations on this.

**Comment by george0st** [comment]
@theSaarco, do you prefer to close this ticket?

**Comment by theSaarco** [comment]
@george0st , sorry for the delay - was out on vacation. You have a valid point that while it is internal there are cases where `spec` members should be accessed directly. I think it will be best to add some documentation, to at least list the parameters which can be useful, and note that this access should usually be read-only.

**Comment by george0st** [comment]
@theSaarco, it will be the best, I have the same view on it, thanks

BTW: can you close this item after add comments?

**Comment by theSaarco** [comment]
Fixed in #2357
