### ISSUE TITLE
[Bug]: Run code on Vscode

### ISSUE THREAD

**Issue by TRINHHOANGANH** [mlrun/mlrun#2881]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of MLRun CE.

### Reproducible Example

```python
from mlrun import new_project, code_to_function
project_dir = './'
project_name = "vehicle-test"
skproj = new_project(project_name, project_dir)
```

### Issue Description

Hi @yaronha !
I'm trying to code in VSCode to create a new project but I am getting this error.
![image](https://user-images.githubusercontent.com/83366198/210946532-fdd9cd6d-c050-49eb-bc2a-ace52c2744b5.png)

Can you give me your solution!

### Expected Behavior

I config vscode like this: https://docs.mlrun.org/en/stable/install/remote.html
![image](https://user-images.githubusercontent.com/83366198/210946975-1285e25a-5993-414c-9a61-118ec5d5140a.png)

### Installation OS

Linux

### Installation Method

Docker

### Python Version

3.8.10

### MLRun Version

1.2.0

**Comment by alonmr** [comment]
Hi @TRINHHOANGANH , if still required, please expand on the installation process. It's clear from the logs that the dbpath is misconfigured. The client uses `mlrun-api` instead of `localhost` like in the mlrun.env. It is possible that the env file is not placed correctly or that something else overrides it. Either way, docker is not maintained ATM so I suggest moving to CE.
