### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by harishgawade1999** [mlrun/mlrun#3300]
**Issue Description** :-
I have a question regarding invoking pipeline after deployment when using "mlrun with docker". 
I'm getting following error which is "TypeError: argument of type 'None Type' is not iterable". 
So can anyone please help me regarding that.

here I'm attaching details- 
**Expected Behavior** - it should get invoked without any error as its getting deployed successfully in the notebook.
**Installation OS** - Windows
**Installation Method** - Docker
**MLRun Version** - 1.2.0
**notebook using** - "04-pipeline" from tutorials.

**Comment by Tankilevitch** [comment]
Hey @harishgawade1999,
Can you please provide the stack trace of the error you receiving?
When running mlrun on docker, only a local pipeline run is available, meaning you need to run the pipeline with `local=True` param. Looking at the 04-pipeline from the tutorials it seems like it will try to run remotely.

**Comment by harishgawade1999** [comment]
> Hey @harishgawade1999, Can you please provide the stack trace of the error you receiving? When running mlrun on docker, only a local pipeline run is available, meaning you need to run the pipeline with `local=True` param. Looking at the 04-pipeline from the tutorials it seems like it will try to run remotely which will cause it to fail because you are not running and k8s which is required to run a KubeFlow pipeline

Okay...i will try and will let u know.

**Comment by harishgawade1999** [comment]
> Hey @harishgawade1999, Can you please provide the stack trace of the error you receiving? When running mlrun on docker, only a local pipeline run is available, meaning you need to run the pipeline with `local=True` param. Looking at the 04-pipeline from the tutorials it seems like it will try to run remotely which will cause it to fail because you are not running and k8s which is required to run a KubeFlow pipeline

I ran workflow using `local=True` param still its getting following error. 

**error: cannot run function at url http://192.168.1.226:53272/v2/models/cancer-classifier/infer, ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))**

**Comment by asafso** [comment]
Having problems getting into Google meet - can I call you at a different numberנOr if you can call me at the number below?+972-54-480-5283Asaf Sent from my iPhoneOn Apr 7, 2023, at 3:46 AM, GAWADE HARISH HANUMANT ***@***.***> wrote:﻿

Hey @harishgawade1999, Can you please provide the stack trace of the error you receiving? When running mlrun on docker, only a local pipeline run is available, meaning you need to run the pipeline with local=True param. Looking at the 04-pipeline from the tutorials it seems like it will try to run remotely which will cause it to fail because you are not running and k8s which is required to run a KubeFlow pipeline

I ran workflow using local=True param still its getting following error.
error: cannot run function at url http://192.168.1.226:53272/v2/models/cancer-classifier/infer, ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by harishgawade1999** [comment]
> Hey @harishgawade1999, Can you please provide the stack trace of the error you receiving? When running mlrun on docker, only a local pipeline run is available, meaning you need to run the pipeline with `local=True` param. Looking at the 04-pipeline from the tutorials it seems like it will try to run remotely which will cause it to fail because you are not running and k8s which is required to run a KubeFlow pipeline

### **How many changes do I need to make in my notebook in order to run the pipeline locally?**

**Comment by harishgawade1999** [comment]
> Hey @harishgawade1999, Can you please provide the stack trace of the error you receiving? When running mlrun on docker, only a local pipeline run is available, meaning you need to run the pipeline with `local=True` param. Looking at the 04-pipeline from the tutorials it seems like it will try to run remotely which will cause it to fail because you are not running and k8s which is required to run a KubeFlow pipeline

### Hey **@Tankilevitch** 
###  How many changes do I need to make in my notebook in order to run the pipeline locally?
