### ISSUE TITLE
[Installation]: 412 HTTP code when creating new projects

### ISSUE THREAD

**Issue by cholojuanito** [mlrun/mlrun#3372]
### Installation check

- [X] I have read the [installation guide](https://docs.mlrun.org/en/latest/install.html).

### Installation OS

Linux

### Installation Method

Docker

### Kubernetes Cluster Type

N/A - Docker

### MLRun CE Version

mlrun/jupyter:1.3.0 mlrun/mlrun-ui:1.3.0

### Issue Description

I've followed everything I can find in the docs about installing MLRun onto my local machine. Try to follow the steps from the quick tutorial but every time I get to the point of running `project = mlrun.get_or_create_project("quick-tutorial", "./", user_project=True)`
All I get is this error message.

```
MLRunPreconditionFailedError: 412 Client Error: Precondition Failed for url: http://localhost:8080/api/v1/projects: Failed creating project tutorial-<name> details: MLRunPreconditionFailedError('API is waiting for migrations to be triggered. Send POST request to [/api/operations/migrations](https://file+.vscode-resource.vscode-cdn.net/api/operations/migrations) to trigger it')
```

I've tried changing client and server versions of MLRun but nothing seems to change this error.

### Installation Logs

<details>
No idea what the installation logs are you are referring to.
</details>

### Additional Information

Running Manjaro linux
Using a Conda virtual env running Python 3.7

**Comment by cholojuanito** [comment]
Any reason this doesn't happen automatically?

**Comment by liranbg** [comment]
@cholojuanito  TBH, for legacy reasons. Old versioned mlrun used sqllite as DB. we migrated it to Mysql and did not want to block pod readiness on migrations since we had large clusters using MLRun and data/schema  migrated took very long. so we preferred to spin pods and spin while their readiness/liveness probes were up to avoid and pod restarts due to timeouts


I believe we will sort it out within next release or so, because now we dont do such migrations (but mainly schema migration)
