### ISSUE TITLE
[Bug]: Current 'make fmt' changed a lot of files (~400)

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#5379]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of MLRun CE.

### Reproducible Example

```python
'make fmt' from https://github.com/george0st/mlrun/blob/development/CONTRIBUTING.md
```

### Issue Description

Current 'make fmt' change a lot of files (~400). I am not sure, that config for fmt is relevant.

### Expected Behavior

Smaller impact

### Installation OS

Windows

### Installation Method

Docker

### Python Version

3.9.10

### MLRun Version

1.6.2

**Comment by alonmr** [comment]
Hey @george0st , we recently moved to ruff linter and indeed it changed a lot of files (see https://github.com/mlrun/mlrun/pull/4796). If you are aligned with development, please check your ruff version.
You should have `ruff==0.3.0`. Since we don't experience this issue, it seems to be an environment problem.

**Comment by george0st** [comment]
@alonmr , it works, many thanks
