### ISSUE TITLE
ImportError: cannot import name 'NewRun' from 'mlrun' (/opt/conda/lib/python3.8/site-packages/mlrun/init.py)

### ISSUE THREAD

**Issue by yifenzhong1920** [mlrun/mlrun#797]
we use single docker
setup as:

SHARED_DIR=~/mlrun-data

docker pull mlrun/jupyter:0.6.1
docker pull mlrun/mlrun-ui:0.6.1

docker network create mlrun-network
docker run -it -p 8080:8080 -p 30040:8888 --rm -d --network mlrun-network --name jupyter -v ${SHARED_DIR}:/home/jovyan/data mlrun/jupyter:0.6.1
docker run -it -p 30050:80 --rm -d --network mlrun-network --name mlrun-ui -e MLRUN_API_PROXY_URL=http://jupyter:8080 mlrun/mlrun-ui:0.6.1

1   when we start script as follow:
from mlrun import NewRun
task = NewRun(handler=handler,name='demo', params={'p1': 5}).with_secrets('file', 'secrets.txt').set_label('type', 'demo')
run = new_function().run

we face this issue:
ImportErrorTraceback (most recent call last)
<ipython-input-11-19373c89aecc> in <module>
----> 1 from mlrun import NewRun
      2 task = NewRun(handler=handler,name='demo', params={'p1': 5}).with_secrets('file', 'secrets.txt').set_label('type', 'demo')
      3 run = new_function().run

ImportError: cannot import name 'NewRun' from 'mlrun' (/opt/conda/lib/python3.8/site-packages/mlrun/__init__.py)

how to fix this problem, thank you

**Comment by Hedingber** [comment]
Hi @yifenzhong1920 - thanks for reporting the issue!
There's no such a thing `NewRun` in MLRun, so you're getting an import error, you probably meant to import `NewTask`.
I would highly suggest you to try out MLRun on a kubernetes cluster - instructions are [here](https://docs.mlrun.org/en/latest/install.html#install-mlrun-on-a-kubernetes-cluster) - it offers way more features, and is generally a much more robust way of using MLRun. you can also try it out through our new katacoda scenario - https://www.katacoda.com/mlrun/scenarios/quick-start
Anyways keep me updated whether your issue was resolved

**Comment by Hedingber** [comment]
No response, closing
