### ISSUE TITLE
Unable to run docs/store/feature-store-demo.ipynb locally

### ISSUE THREAD

**Issue by ddanieltan** [mlrun/mlrun#864]
Hi, I'm trying to test the functionality of the feature store locally by running the notebook from this [documents page](https://docs.mlrun.org/en/v0.6.1/store/feature-store-demo.html).

I updated the initial setup to try and run the notebook and mlrun service locally like so
```
import mlrun
from mlrun import mlconf
from os import path
mlconf.dbpath = mlconf.dbpath or './'
mlconf.artifact_path = mlconf.artifact_path or path.abspath('./data')
mlrun.set_environment(project="stocks",user_project=True)
```

However upon this call `fs.ingest(stocks_set, stocks, infer_options=fs.InferOptions.default())`
I'm seeing this error trace
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-16-cad8c1ae0f89> in <module>
      1 # add feature set without time column (stock ticker metadata)
      2 stocks_set = fs.FeatureSet("stocks", entities=[fs.Entity("ticker")])
----> 3 fs.ingest(stocks_set, stocks, infer_options=fs.InferOptions.default())

~/miniconda3/envs/mlrun/lib/python3.7/site-packages/mlrun/feature_store/api.py in ingest(featureset, source, targets, namespace, return_df, infer_options, run_config, mlrun_context, spark_context, transformer)
    242     )
    243     return_df = return_df or infer_stats != InferOptions.Null
--> 244     featureset.save()
    245 
    246     targets = targets or featureset.spec.targets or get_default_targets()

~/miniconda3/envs/mlrun/lib/python3.7/site-packages/mlrun/feature_store/feature_set.py in save(self, tag, versioned)
    399             "features", []
    400         )  # bypass DB bug
--> 401         db.store_feature_set(as_dict, tag=tag, versioned=versioned)
    402 
    403     def reload(self, update_spec=True):

~/miniconda3/envs/mlrun/lib/python3.7/site-packages/mlrun/db/filedb.py in store_feature_set(self, feature_set, name, project, tag, uid, versioned)
    560         self, feature_set, name=None, project="", tag=None, uid=None, versioned=True
    561     ):
--> 562         raise NotImplementedError()
    563 
    564     def patch_feature_set(

NotImplementedError: 
```

I gather that because I'm running mlrun locally, functions such as `db.store_feature_set()` is not working. Is it possible to have this notebook example updated to run a demo of the feature store locally?

**Comment by Hedingber** [comment]
Hi @ddanieltan - thanks for reporting the issue! and sorry it took me time to respond
In order to enjoy the full power of MLRun you need more than just `pip install` the package, another essential component here is the mlrun-api, which the package works with.
I would highly suggest you to try this with our mlrun-kit - which is an helm chart that brings you everything (mlrun ui&api, jupyter, nuclio and much more) baked in and integrated so you won't need to waste your time on configurations.
You can find the installation instructions here - https://docs.mlrun.org/en/latest/install.html#install-mlrun-on-a-kubernetes-cluster
Let me know how it worked out for you

**Comment by Hedingber** [comment]
Closing
